version: '3'
services:
  # RabbitMQ Docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sretnesapicenet

#mssql docker
  sretnesapice-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SretneSapice123
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - sretnesapicenet

  sretnesapice-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=sretnesapice-sql,1433;Database=IB180148_docker;User=sa;Password=SretneSapice123;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=sretnesapice@outlook.com
      - SMTP_PASSWORD=sapice123
    ports:
      - 7094:7094
    networks:
      - sretnesapicenet
    links:
      - sretnesapice-sql
    depends_on:
      - sretnesapice-sql
      - rabbitmq

        # RabbitMQ Service Docker
  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./SretneSapice.Subscriber/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=sretnesapice@outlook.com
      - SMTP_PASSWORD=sapice123
    depends_on:
      - rabbitmq
    networks:
      - sretnesapicenet
      
networks:
  sretnesapicenet:
    driver: bridge     